const Components = [
  {
    title: 'Badge',
    html: 'vlt-badge',
    icon: 'bookmark',
    propertyRows: [
      { property: 'color', type: 'String' },
      { property: 'dismissable', type: 'Boolean', default: true },
    ],
    eventRows: [
      { event: 'dismissed', description: 'when the badge is dismissed' },
    ],
  },
  {
    title: 'Button',
    html: 'vlt-button',
    icon: 'circle-nested',
    propertyRows: [
      { property: 'app', type: 'Boolean', default: false },
      { property: 'destructive', type: 'Boolean', default: false },
      { property: 'disabled', type: 'Boolean', default: false },
      { property: 'icon', type: 'String' },
      { property: 'large', type: 'Boolean', default: false },
      { property: 'primary', type: 'Boolean', default: false },
      { property: 'quaternary', type: 'Boolean', default: false },
      { property: 'secondary', type: 'Boolean', default: false },
      { property: 'small', type: 'Boolean', default: false },
      { property: 'spin', type: 'Boolean', default: false },
      { property: 'tooltip-title', type: 'String' },
    ],
  },
  {
    title: 'Callout',
    html: 'vlt-callout',
    icon: 'shout',
    propertyRows: [
      { property: 'critical', type: 'Boolean' },
      { property: 'good', type: 'Boolean' },
      { property: 'tip', type: 'Boolean' },
      { property: 'shoutout', type: 'Boolean' },
      { property: 'warning', type: 'Boolean' },
    ],
  },
  {
    title: 'Checkbox',
    html: 'vlt-checkbox',
    icon: 'checkbox',
    propertyRows: [
      { property: 'checked', type: 'Boolean', default: false },
      { property: 'disabled', type: 'Boolean', default: false },
      { property: 'id', type: 'String' },
      { property: 'inline', type: 'Boolean', default: false },
      { property: 'label', type: 'String' },
      { property: 'tooltip-position', type: 'String', default: 'left' },
      { property: 'tooltip-title', type: 'String' },
    ],
  },
  {
    title: 'Dropdown',
    html: 'vlt-dropdown',
    icon: 'circle-down',
    propertyRows: [
      { property: 'id', type: 'String' },
      { property: 'label', type: 'String' },
      { property: 'selected', type: 'String', default: 'the first option in the options array' },
      { property: 'show-selection', type: 'Boolean' },
    ],
  },
  {
    title: 'Field',
    html: 'vlt-field',
    description: 'Wraps an input element',
    icon: 'image',
    propertyRows: [
      { property: 'big', type: 'Boolean', default: false },
      { property: 'elastic', type: 'Boolean', default: false },
      { property: 'error-message', type: 'String' },
      { property: 'label', type: 'String' },
      { property: 'optional', type: 'Boolean', default: false },
      { property: 'tooltip', type: 'String' },
    ],
  },
  {
    title: 'Icon',
    html: 'vlt-icon',
    icon: 'info',
    propertyRows: [
      { property: 'icon', type: 'String' },
      { property: 'clickable', type: 'Boolean', default: false },
      { property: 'color', type: 'String' },
      { property: 'no-class', type: 'Boolean', default: false },
      { property: 'pointer', type: 'Boolean', default: false },
      { property: 'spin', type: 'Boolean', default: false },
      { property: 'small', type: 'Boolean', default: false },
    ],
  },
  {
    title: 'Input',
    html: 'vlt-input',
    icon: 'type',
    propertyRows: [
      { property: 'disabled', type: 'Boolean', default: false },
      { property: 'hint', type: 'String' },
      { property: 'id', type: 'String' },
      { property: 'label', type: 'String' },
      { property: 'max', type: 'Number' },
      { property: 'maxlength', type: 'Number' },
      { property: 'min', type: 'Number' },
      { property: 'placeholder', type: 'String' },
      { property: 'textarea', type: 'Boolean', default: false },
      { property: 'type', type: 'String', default: 'text' },
      { property: 'val', type: 'String | Number' },
    ],
  },
  {
    title: 'Modal',
    html: 'vlt-modal',
    icon: 'modal',
    propertyRows: [
      { property: 'can-canel', type: 'Boolean', default: true },
      { property: 'cancel-text', type: 'String' },
      { property: 'confirm-btn-icon', type: 'String' },
      { property: 'destructive', type: 'Boolean', default: false },
      { property: 'dynamic', type: 'Boolean', default: false },
      { property: 'extra-btn-class', type: 'String' },
      { property: 'extra-btn-icon', type: 'String' },
      { property: 'extra-btn-label', type: 'String' },
      { property: 'id', type: 'String' },
      { property: 'large', type: 'Boolean', default: false },
      { property: 'message', type: 'String' },
      { property: 'notify', type: 'Boolean', default: false },
      { property: 'ok-text', type: 'String' },
      { property: 'title', type: 'String' },
      { property: 'visible', type: 'Boolean', default: false },
    ],
    eventRows: [
      { event: 'close', description: 'when the modal is cancelled' },
      { event: 'confirm', description: 'when the modal is confirmed' },
      { event: 'extraBtnClick', description: 'when the extra button is clicked' },
    ],
  },
  {
    title: 'Radio',
    html: 'vlt-radio',
    icon: 'check-circle',
    propertyRows: [
      { property: 'checked', type: 'Boolean', default: false },
      { property: 'hint', type: 'String' },
      { property: 'inline', type: 'Boolean', default: false },
      { property: 'label', type: 'String' },
      { property: 'name', type: 'String' },
      { property: 'val', type: 'String' },
    ],
  },
  {
    title: 'Select',
    html: 'vlt-select',
    icon: 'cursor',
    propertyRows: [
      { property: 'id', type: 'String' },
      { property: 'options', type: 'Array' },
    ],
  },
  {
    title: 'Sidemenu',
    html: 'vlt-sidemenu',
    icon: 'menu',
  },
  {
    title: 'Sidemenu item',
    html: 'vlt-sidemenu-item',
    icon: 'menu',
    propertyRows: [
      { property: 'color', type: 'String' },
      { property: 'trigger-icon', type: 'String' },
      { property: 'trigger-label', type: 'String' },
    ],
  },
  {
    title: 'Sidemenu link',
    html: 'vlt-sidemenu-link',
    icon: 'menu',
    propertyRows: [
      { property: 'color', type: 'String' },
      { property: 'external', type: 'Boolean' },
      { property: 'href', type: 'String' },
      { property: 'icon', type: 'String' },
      { property: 'label', type: 'String' },
      { property: 'to', type: 'String' },
    ],
  },
  {
    title: 'Sidemenu title',
    html: 'vlt-sidemenu-title',
    icon: 'menu',
    propertyRows: [
      { property: 'label', type: 'String' },
    ],
  },
  {
    title: 'Spinner',
    html: 'vlt-spinner',
    icon: 'reload',
    propertyRows: [
      { property: 'small', type: 'Boolean' },
    ],
  },
  {
    title: 'Steps',
    html: 'vlt-steps',
    icon: 'more-negative',
    propertyRows: [
      { property: 'count', type: 'Number' },
      { property: 'selected', type: 'Number' },
      { property: 'steps', type: 'Array' },
    ],
  },
  {
    title: 'Switch',
    html: 'vlt-switch',
    icon: 'switch',
    propertyRows: [
      { property: 'checked', type: 'Boolean', default: false },
      { property: 'red', type: 'Boolean', default: false },
      { property: 'small', type: 'Boolean', default: false },
    ],
  },
  {
    title: 'Tabs',
    html: 'vlt-tabs',
    icon: 'tabs',
    propertyRows: [
      { property: 'icon', type: 'Boolean', default: false },
    ],
  },
  {
    title: 'Tab',
    html: 'vlt-tab',
    icon: 'tabs',
    propertyRows: [
      { property: 'disabled', type: 'Boolean', default: false },
      { property: 'icon', type: 'String' },
      { property: 'label', type: 'String' },
    ],
  },
  {
    title: 'Table',
    html: 'vlt-table',
    icon: 'table-1',
    propertyRows: [
      { property: 'columns', type: 'Array' },
      { property: 'current-page', type: 'Number', default: 1 },
      { property: 'pagination', type: 'Boolean', default: false },
      { property: 'page-size', type: 'Number', default: 20 },
      { property: 'rows', type: 'Array' },
      { property: 'total', type: 'Number', default: 0 },
    ],
  },
  {
    title: 'Title',
    html: 'vlt-title',
    icon: 'cursor',
    propertyRows: [
      { property: 'color', type: 'String' },
      { property: 'icon', type: 'String' },
      { property: 'title', type: 'String' },
    ],
  },
  {
    title: 'Tooltip',
    html: 'vlt-tooltip',
    icon: 'tooltip',
    propertyRows: [
      { property: 'position', type: 'String', default: 'left' },
      { property: 'title', type: 'String' },
    ],
  },
];

export default Components;
